openapi: 3.0.0
info:
  title: OpenStudent
  version: "1.0"
servers:
  - url: "http://localhost:3001"
    description: DEV server
components:
  parameters:
    runIdParam:
      name: runId
      in: query
      schema:
        type: integer
        maximum: 6
        minimum: 1
      description: grading period
    runDateParam:
      name: runDate
      in: query
      schema:
        type: string
      description: date in format DD/MM/YYYY
    allParam:
      name: all
      in: query
      schema:
        type: boolean
      description: want all records?
    alertsParam:
      name: alerts
      in: query
      schema:
        type: boolean
      description: want teacher comments?
    alertsScoreParam:
      name: alertsScore
      in: query
      schema:
        type: number
      description: get alerts when grade drops below score
    studentIdParam:
      name: id
      in: path
      required: true
      schema:
        type: string
      description: student identifier
  schemas:
    classwork:
      title: classwork
      type: object
      properties:
        dateDue:
          type: string
          description: date assignment was due
        dateDueMs:
          type: number
          description: "date due, in milliseconds"
        dateAssigned:
          type: string
          description: date assigned
        assignment:
          type: string
          description: description for assignment
        score:
          type: number
          description: score for assignment
        weightedScore:
          type: string
          description: weighted score for assignment
        weightedTotalPoints:
          type: string
          description: total weighted points possible for assignment
        comment:
          type: string
          description: comment on assignment
    interval:
      title: interval
      type: object
      properties:
        start:
          type: number
          description: interval start in milliseconds
        end:
          type: number
          description: interval end in milliseconds
        gradingPeriod:
          type: object
          description: grading period
          properties:
            first:
              type: number
              description: first available period
            prev:
              type: number
              description: previous period
            current:
              type: number
              description: active period
            next:
              type: number
              description: next period
            last:
              type: number
              description: last available period
paths:
  /students:
    get:
      operationId: get-students
      summary: Get all student records
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - studentId
                  - studentName
                  - grade
                  - gradingPeriod
                  - school
                  - studentUrl
                properties:
                  studentId:
                    type: number
                    description: student identifier
                  studentName:
                    type: string
                    description: student name
                  grade:
                    type: string
                    description: current grade level
                  gradingPeriod:
                    type: number
                    description: current Grading Period
                  school:
                    type: string
                    description: current school name
                  studentUrl:
                    type: string
                    description: HATEOS link to student details
        "400":
          description: Bad Request
  "/students/{id}":
    parameters:
      - $ref: "#/components/parameters/studentIdParam"
    get:
      operationId: get-student-id
      summary: Get individual student record
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - studentId
                  - studentName
                  - grade
                  - gradingPeriod
                  - building
                  - homeroom
                  - classworkUrl
                  - gradesUrl
                  - gradesAverageUrl
                properties:
                  studentId:
                    description: student identifier
                    type: number
                  studentName:
                    type: string
                    description: student name
                  grade:
                    type: string
                    description: current grade level
                  gradingPeriod:
                    type: number
                    description: current Grading Period
                  building:
                    type: string
                    description: current school name
                  homeroom:
                    type: object
                    description: homeroom
                    properties:
                      room:
                        type: string
                        description: room number
                      teacher:
                        type: string
                        description: "teacher last name, first name"
                  courses:
                    type: array
                    items:
                      type: string
                      description: course identifiers
                  classworkUrl:
                    type: string
                    description: HATEOS link to student classwork
                  gradesUrl:
                    type: string
                    description: HATEOS link to student grades
                  gradesAverageUrl:
                    type: string
                    description: HATEOS link to student grade averages
        "400":
          description: Bad Request
  "/students/{id}/classwork":
    parameters:
      - $ref: "#/components/parameters/studentIdParam"
    get:
      operationId: get-students-id-classwork
      summary: Get student classwork records
      tags: []
      parameters:
        - $ref: "#/components/parameters/runIdParam"
        - $ref: "#/components/parameters/runDateParam"
        - $ref: "#/components/parameters/allParam"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - studentId
                  - studentName
                  - interval
                  - assignments
                properties:
                  studentId:
                    type: string
                    description: student identifier
                  studentName:
                    type: string
                    description: student name
                  interval:
                    $ref: "#/components/schemas/interval"
                  assignments:
                    type: array
                    items:
                      $ref: "#/components/schemas/classwork"
        "400":
          description: Bad Request
  "/students/{id}/grades":
    parameters:
      - $ref: "#/components/parameters/studentIdParam"
    get:
      operationId: get-students-id-grades
      summary: Get student grades
      tags: []
      parameters:
        - $ref: "#/components/parameters/runIdParam"
        - $ref: "#/components/parameters/runDateParam"
        - $ref: "#/components/parameters/allParam"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - studentId
                  - studentName
                  - courseGrades
                  - gradesAverageUrl
                properties:
                  studentId:
                    type: string
                    description: student identifier
                  studentName:
                    type: string
                    description: student name
                  courseGrades:
                    type: object
                    properties:
                      "{courseId}":
                        type: object
                        description: course identifier (as key)
                        properties:
                          "{category}":
                            type: array
                            description: category name (as key)
                            items:
                              type: number
                              description: scores for assignments
                  gradesAverageUrl:
                    type: string
                    description: HATEOS link to grade averages
  "/students/{id}/grades/average":
    parameters:
      - $ref: "#/components/parameters/studentIdParam"
    get:
      operationId: get-students-id-grades-average
      summary: Get student grade averages
      tags: []
      parameters:
        - $ref: "#/components/parameters/runIdParam"
        - $ref: "#/components/parameters/runDateParam"
        - $ref: "#/components/parameters/allParam"
        - $ref: "#/components/parameters/alertsParam"
        - $ref: "#/components/parameters/alertsScoreParam"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - studentId
                  - studentName
                  - grades
                properties:
                  studentId:
                    type: string
                    description: student identifier
                  studentName:
                    type: string
                    description: student name
                  alerts:
                    type: array
                    description: alerts for low scores and comments
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          description: assignment due date
                        course:
                          type: string
                          description: course name
                        assignment:
                          type: string
                          description: assignment description
                        score:
                          type: number
                          description: assignment score
                        comment:
                          type: string
                          description: assignment comment
                  grades:
                    type: object
                    required:
                      - courseId
                      - courseName
                    properties:
                      courseId:
                        type: string
                        description: course identifier
                      courseName:
                        type: string
                        description: course name
                      average:
                        type: number
                        description: course average
